### PR TITLE
add media tags support

### PR DESCRIPTION
**Pull request by AlexKovalevych**
Sorry, didn't have a chance to add tests yet, hope i can add them soon :)

### CODE REVIEW

**Comment by desarrolla2** [comment]
I need to review your PR with calm, so, i see that you are looking for no standart tags as 'content', 'keywords', 'thumbnail', 'category'.

You can see the specification here http://cyber.law.harvard.edu/rss/rss.html

Maybe you can provide a link example with this keys?

**Comment by desarrolla2** [comment]
Probably i need to create a plugin system to parse rss enriched

**Comment by AlexKovalevych** [comment]
right, i took it from here http://www.rssboard.org/media-rss
xml example in the associated bundle issue
i think it may be useful in many cases, if no media tags provided nothing is changed, of course if see it not part of the system, there should be a way to allow adding custom parse logic.

**Comment by desarrolla2** [comment]
HI @AlexKovalevych 

I just implemented the funcionality, you can see how use it here https://github.com/desarrolla2/RSSClient/blob/master/doc/custom-process.md

I was created a RSSMediaProcessor, and put in here https://github.com/desarrolla2/RSSClient/blob/master/src/Desarrolla2/RSSClient/Parser/Processor/RSS/RSSMediaProcessor.php

Now you need a valid example, that you are using for create test for this.

What do you think about?

**Pull request closed without merging**
